#!/bin/bash
#API Example  => curl http://11.1.1.3/api/v1/getwinner
for i in $( seq 1 1 60 );do
#	for j in $( seq 1 100 );do 
		(crontab -l ; echo "* * * * * sleep $i; bash ./status_codes $1 $2 >> ./codes.txt")  | crontab -
#	done
done

