#!/bin/bash
#API => curl http://11.1.1.3/api/v1/getwinner
for i in $( seq 1 1 60 );do
	for j in $( seq 1 100 );do 
		(crontab -l ; echo "* * * * * sleep $i; bash /home/mrtshoot/zeus/status_codes $1 $2 >> /home/mrtshoot/zeus/codes.txt" ) | crontab -
	done
done
